react-native-reanimated
react-native-gesture-handler
react-native-screens
react-native-safe-area-context
@react-native-community/masked-view
@react-navigation/native
@react-navigation/bottom-tabs
@react-navigation/stack
react-native-vector-icons
